#!/bin/sh
set -e
# Automatically added by package maintainer
if [ "$1" = purge ]; then
    rm -f /etc/tinc/nets.boot
    update-rc.d tinc remove >/dev/null 2>/dev/null
fi
# End automatically added section

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

